tokio-trace/src/lib.rs, tokio-trace/src/span.rs
This branch makes the following minor changes: 
+ Add `field` methods to `Event` and `SpanData` allowing optional 
access to an individual field value by name 
+ Add `SpanData::parents` and `SpanData::all_fields` methods, by
analogy to the methods of the same names on `Event`
+ Add RustDoc to `SpanData` and `Event` public API methods
=> Miscellaneous cleanup & docs work

tokio-trace/Cargo.toml, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs
Fixes #10. Also required for #20.
Currently, any span created at the top level is implicitly a child of
the "root span" that is created when the program starts and lasts for
its entire lifespan. Removing the implicit root span would allow
subscribers to more easily distinguish between "separate" traces, such
as per-request traces in a server application. 
See also:
+ https://github.com/hawkw/tokio-trace-prototype/issues/4#issuecomment-424165691  
+ https://github.com/hawkw/tokio-trace-prototype/issues/4#issuecomment-424167537
Also, the implicit root span is an artifact of prior implementation 
constraints and it is no longer required.
This branch removes the implicit root span. It also removes the
dependency on the `lazy_static` crate.
Note that this also changes the `event.parent` field …
=> Remove implicit root span

tokio-trace-log/Cargo.toml, tokio-trace-log/src/lib.rs, tokio-trace/Cargo.toml, tokio-trace/examples/basic.rs, tokio-trace/src/lib.rs, tokio-trace/src/subscriber.rs
This means that the core `tokio_trace` crate no longer has to depend on `log`; see #20.
=> Move `log` compatibility code to its own crate

Cargo.toml, tokio-trace-env-logger/Cargo.toml, tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-futures/Cargo.toml, tokio-trace-futures/src/lib.rs, tokio-trace-log/Cargo.toml, tokio-trace-tower-http/Cargo.toml, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace-tower-http/src/lib.rs, tokio-trace-tower/Cargo.toml, tokio-trace-tower/src/lib.rs, tokio-trace/Cargo.toml, tokio-trace/src/lib.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
Closes #20. Also needed for #23.
This PR moves the instrumented future types to their own separate crate.
=> Move futures compatibility code to a new `tokio-trace-futures` crate

tokio-trace-log/src/lib.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
This branch changes the semantics of that function to be "notifying the
subscriber of the creation of a new span", rather than simply
"requesting a new ID".
This introduces some new guarantees to the `new_span` API (as discussed
in
https://github.com/hawkw/tokio-trace-prototype/commit/f7bc34651e980e0a08dd599b25737df7656c7a18#r30777026),
but I think they can reasonably addressed as part of future changes.
=> Turn `new_span_id` into `new_span`

tokio-trace-log/src/lib.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
Fixes #24.
Requires #34.
Currently, spans and events both have `std::time::Instant` fields that
record a timestamp of when the span or event was created. Furthermore,
the `Subscriber::enter` and `Subscriber::exit` trait methods take an
`Instant` argument representing a timestamp of when the span was entered
or exited. As described in #24, this is a potential performance issue,
as `Instant::now` may result in an expensive syscall. Since some
subscriber implementations may not need timestamps, or may not need to
record them for _all_ possible events, we should not perform these
syscalls by default.
This branch removes the timestamps from spans and events, and from the
`Subscriber` API. If subscribers require timestamps for events or spans,
they can call `Instant::now` or `SystemTime::now`. …
=> Remove timestamps from spans and events

tokio-trace/src/lib.rs, tokio-trace/src/subscriber.rs
Fixes #27.
Currently, every time a `Span` or `Event` is constructed, we test if the
current subscriber cares about it, by calling `Subscriber::enabled` with
the `Span`/`Event`'s metadata. If this function returns false, we don't
construct the span or send the event. However, this means that the
implementation of `enabled` has to be run every time a span or event is
created. If the filtering is expensive (such as a regular expression or
string comparison), this can have a noticeable performance cost.
This branch changes the `span!` and `event!` macros to cache the result
of previous calls to `Subscriber::enabled`, so that filters don't have
to be re-evaluated. Subscribers are given the ability to invalidate
their previously cached filter results, which they may do for various
reasons --- …
=> Cache the result of evaluating filters

tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-log/src/lib.rs, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace/examples/basic.rs, tokio-trace/examples/sloggish/main.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
Fixes #30. Fixes #29.
Currently, the `tokio_trace` crate provides a global dispatcher through
which all trace events are set. This was based primarily on the design
of the `log` crate. 
As described in #30, this is not an ideal design. Instead, there should
be no global subscriber state. The Tokio runtime will handle setting up
the subscriber at the root of the task. When operating outside of a
Tokio runtime, the user will be responsible for setting up the necessary
subscriber. There should be a way to get a handle to the current
subscriber and probably easy ways to get into new execution while
carrying over the subscriber.
This branch removes the global dispatcher, and replaces it with an
explicit contextual dispatcher. In doing so, it also removes the fanout
functionality from the …
=> Remove global dispatcher

Cargo.toml, tokio-trace-log/Cargo.toml, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/Cargo.toml, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/filter.rs, tokio-trace-subscriber/src/lib.rs, tokio-trace-subscriber/src/observe.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace/examples/basic.rs, tokio-trace/src/subscriber.rs
As discussed in #40, we can implement a lot of the functionality which
previously would require a global dispatcher in terms of traits
representing _subsets_ of the `Subscriber` API. `Subscriber` has some
trait methods which ought to be user-customizable, but also don't
compose well --- it doesn't make sense to have multiple subscribers
active in a given scope each generating their own span IDs, for example.
However, selected subsets of the subscriber API _can_ be composed,
allowing us to implement features like fan-out in terms of just the
portion that observes spans and events, with a single source of truth
for span ID generation.
For example, I imagine an application being able to compose subscribers
like this:
```rust
subscriber::Composed::builder() …
```
=> Introduce a `tokio-trace-subscriber` crate

tokio-trace-futures/src/executor.rs, tokio-trace-futures/src/lib.rs
This branch adds functionality to the `tokio-trace-futures`
compatibility crate for instrumenting future _executors_ as well as
futures. Instrumenting a future with a span works slightly differently
than instrumenting a future --- rather than taking a span which is
entered by all futures spawned on the executor, it takes a _function_
returning a span, so that all top-level futures spawned are inside of
their own unique span. This seemed like the correct behaviour for
executors.
Possibly more valuable is the ability to attach a `Subscriber` to an
executor, so that whenever futures spawned on that executor are polled,
the subscriber context switches to the attached subscriber.
=> Instrument future executors as well as futures

tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/filter.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/lib.rs
Fixes #36.
This branch makes some minor changes to the `Meta` type: 
+ Metadata now knows if it corresponds to a Span or an Event, and has
`is_span`/`is_event` methods.
+ Made the `target` field non-optional, and the `module_path`, `file`, 
and `line` fields optional. This mirrors what the `log` crate does,
and is more correct --- metadata that is created manually rather than
by a macro may not know its source code location, but must have a 
target.
+ When creating metadata without a specified target, the module path
is used. Again, this is what `log` does.
+ Added new filters: `only_targets`, `except_targets`, `spans_only`
and `events_only`. What they do should be fairly obvious.
+ Changes to internal macros to support these changes.
=> Minor improvements to metadata

tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/registry.rs
This is a minor improvement to the `tokio-trace-log` crate that makes
the formatting of fields in spans/events consistent with the way the
rest of the log record is formatted.
Before:
```
➜ cargo run --example basic -p tokio-trace
Finished dev [unoptimized + debuginfo] target(s) in 0.20s
Running `target/debug/examples/basic`
INFO 2018-10-18T18:15:05Z: basic: hello world; in_span=None; { foo: 3, bar: "bar" };
TRACE 2018-10-18T18:15:05Z: basic: new_span: my_great_span { foo: 4, baz: 5 }; span=Id(0); parent=None;
TRACE 2018-10-18T18:15:05Z: enter: span=Id(0); state=Running;
INFO 2018-10-18T18:15:05Z: basic: hi from inside my span; in_span=Some(Id(0)); { yak_shaved: true };
TRACE 2018-10-18T18:15:05Z: exit: id=Id(0); state=Done;
```
After:
```
➜ cargo run --example basic -p tokio-trace …
```
=> Make trace logger field formatting more consistent

tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-futures/src/lib.rs, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/observe.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace-tower-http/Cargo.toml, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace-tower-http/src/lib.rs, tokio-trace-tower/src/lib.rs, tokio-trace/examples/basic.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/main.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs, tokio-trace/src/value.rs
The current representation of values for span and event fields has some
significant issues:
+ It always allocates span values on the heap, even when the subscriber
immediately discards them,
+ It completely erases the original type of the value, and treats it
as a `fmt::Debug` trait object,
+ Values implementing both `Display` and `Debug` are always formatted
using `Debug`, while values implementing only `Display` cannot be
created.
However, representing values as trait objects does have one significant
advantage: it allows arbitrary user-defined types to be used as values,
rather than restricting them to a set of Rust primitives. While this is
not _strictly_ necessary, it is nice to allow complex user-defined
types to be treated as field values. 
This is especially worth considering …
=> Better family values

.travis.yml, tokio-trace/src/span.rs
This branch adds a rustfmt stage to the `tokio-trace` CI job. It's run
in a separate stage from the tests so that Travis' UI makes it clearer
whether the rustfmt check or the tests are failing. 
Note that this runs with the _stable_ rustfmt. This means that if you
run the nightly rustfmt, you may get formatting that's inconsistent with
what CI expects. I decided to go with stable here as its formatting will
change less frequently, so we don't get a constantly-broken CI build as
a result of not running `rustup update rustfmt` every morning.
=> Start running rustfmt on CI

tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
This branch adds `Subscriber` and `Span` methods for annotating spans
with prior spans from which they follow. For the most part, this branch
doesn't add implementations of this interface for now, besides proxying
to it in composite subscribers.
It would be good to get a review of the interface before getting too deep 
into implementation.
=> Add trait methods for `follows_from`

tokio-trace-futures/src/lib.rs, tokio-trace/src/subscriber.rs
This fixes an issue where the tests in the `tokio-trace-futures` crate
weren't actually making any assertions. 
`MockSubscriber::run()` _used_ to set the mock subscriber as the current
subscriber, but that behaviour changed in #40. Now, it's necessary to
use `Dispatch::to(...).with(...)` to set the subscriber context. The
tests in the core crate were updated, but the `tokio-trace-futures`
tests evidentally weren't.
=> Fix tokio-trace-futures tests not actually doing anything

tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-futures/src/lib.rs, tokio-trace-macros/examples/basic.rs, tokio-trace-subscriber/src/filter.rs, tokio-trace-subscriber/src/observe.rs, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace/examples/basic.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/main.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
Currently, spans have a reference to the dispatcher in whose context
they were created. When those spans are entered or exited, the
enter/exit notifications are sent to that dispatcher rather than the
thread's current dispatcher.
However in the current design, when we’re inside of a given span, if we
enter a new child of that span, that span is created with the _thread's_
current dispatcher, _not_ the dispatcher for the current span's parent.
That means that if the thread's current default dispatcher changes,
parts of a trace tree can be collected by two different dispatchers.
This is a problem.
Dispatchers should be able to collect whole trace trees, as span IDs are
only expected to be meaningful within the context of a dispatcher. For
example, if a new child span is created in the …
=> Make the dispatcher sticky

tokio-trace/Cargo.toml, tokio-trace/src/lib.rs
This was supposed to be removed in #33 but I must've missed it.
Closes #56.
=> Remove futures dependency from core crate

tokio-trace/benches/no_subscriber.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/lib.rs
When a call site caches a filter evaluation for a particular piece of
metadata, the cached filter result will need to be evaluated if the
subscriber context changes. These subscribers may have different filters
which may return different results for the same metadata, so we must not
use the cached result from one subscriber when the current subscriber
has changed.
Currently, this invalidation is implemented by having the dispatcher
track a set of the hashes of all the callsites it has filtered since the
last subscriber switch. This has serious performance implementations.
This branch changes the approach to have the call-site store an ID of
the last subscriber that filtered it, and assigning a unique ID to every
new dispatcher that's created. By comparing the ID of the current
dispatcher …
=> Make callsite cache invalidation much faster

tokio-trace/src/callsite.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/lib.rs
This branch refactors the callsite caching code to use a `struct` to
bundle together the caches, and struct methods rather than macros to
interact with the cache. This puts us on the path to eventually
exporting a public API for the callsite cache to the other crates.
This doesn't have a significant impact on the existing benchmarks:
```
Running target/release/deps/no_subscriber-9424dd66075149b8
running 3 tests
test bench_1_atomic_load         ... bench:           0 ns/iter (+/- 0)
test bench_no_span_no_subscriber ... bench:           0 ns/iter (+/- 0)
test bench_span_no_subscriber    ... bench:          31 ns/iter (+/- 0)
```
=> Give callsite caches a slightly nicer API

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/span.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs
This branch changes the `prior_span` naming back to `follows_from`. This
naming better implies causality.
Closes #59 
=> Rename `prior_span` back to `follows_from`

tokio-trace-core/src/callsite.rs, tokio-trace-core/src/lib.rs, tokio-trace/src/lib.rs
This branch is an attempt to hide more of the implementation details
behind the callsite cache, so that it can become part of a public API. 
Unfortunately, the `Cache` type still needs to be `#[doc(hidden)] pub`,
as it still needs to be constructed in a macro so that the appropriate
number of thread-locals are generated (per-callsite, not globally within
the `new` function), but the fields can now be private, and the `span!`
and `event!` macros are now written against an API that doesn't expose
the thread-local behind the cache. So, this is a step in the right
direction, I hope.
Also, callsites can now construct `Span`s. Hopefully this will allow us
to avoid exposing the "is the span disabled" logic, while also providing
a way to construct spans other than using the span macro.
For future …
=> Attempt to encapsulate the callsite cache's thread-locality

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/span.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-futures/src/lib.rs, tokio-trace-log/src/lib.rs, tokio-trace-macros/examples/basic.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/observe.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace-tower-http/src/lib.rs, tokio-trace-tower/src/lib.rs, tokio-trace/examples/basic.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/main.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
This branch represents a significant rewrite of the span type and its
API. The primary goal of this change is that constructing an enabled
span should not cause an allocation (see #25), and a single `Span`
handle should be able to be entered multiple times (see #28).
This change necessitated several API changes:
- `Spans` are now entered by mutable reference, rather than by consuming
the span,
- `Span` no longer implements `Clone`,
- Removed the `span::State` type, and removed it from all `Subscriber` 
methods.
- `Subscriber`s are now notified of span closure by a new 
`Subscriber::close(span id)` method.
- Dropping a `Span` handle will still cause a the span to be closed
the next time it exits, if no other handles exist. However, spans may
now be asked to close explicitly with the new …
=> Rework span entry and exit APIs

tokio-trace-core/src/callsite.rs, tokio-trace-core/src/dispatcher.rs, tokio-trace/benches/no_subscriber.rs, tokio-trace/src/lib.rs
This branch changes the interface between the callsite cache and the
dispatcher, adding a `Dispatcher::if_enabled` method which, given a
closure and a callsite, executes the closure if the callsite is enabled
on that dispatcher. This function is publicly exposed and documented,
and can be used as the basis for span and event construction in the
`span!` and `event!` macros.
The motivation behind this is twofold:
First, the `span!` macro currently calls `add_value` on the for each
value, regardless of whether or not the span is enabled. If the span is
disabled, adding the value is a no-op, but since the macro takes the
value as an expression, that expression still has to be evaluated before
passing it to `add_value`. Thus, values which are expensive to produce
still incur a cost. I added a …
=> Add `Dispatcher::if_enabled` function

tokio-trace-core/src/span.rs, tokio-trace/src/span.rs
Closes #79.
This branch removes the `span::AsId` trait. This was added in order to
improve API ergonomics, but it isn't really necessary and shouldn't be
in `-core`.
=> Remove `AsId`

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/observe.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs
Closes #78.
This branch removes the second lifetime parameter for an `Event`'s
metadata. That lifetime parameter may have been necessary at one point
but it doesn't appear to be now, and it just complicates things
needlessly.
=> Remove unnecessary second lifetime from `Event`

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/span.rs, tokio-trace-log/src/lib.rs, tokio-trace/src/lib.rs
This branch removes `Dispatch::current` from the public API.
As @carllerche pointed out to me, with some reworking of APIs, it's
possible to implement span and event creation without requiring a
dispatcher to be passed in. This means that we no longer have to observe
the current dispatcher.
Removing the current dispatcher means that we can prevent a lot of bad
behaviour that's otherwise exposed to users --- the current dispatcher
can no longer be "forced" to observe events or spans by calling its
notification methods manually.
The new `Span` and `Event` constructors are also (finally) in a state
that I'm actually comfortable stabilizing as public APIs, so I've
un-hidden them. This means that the `span!` and `event!` macros no
longer rely on `#[doc(hidden)]` public functions, with the …
=> Improve span/event construction APIs

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/field.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/span.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/span.rs
Closes #25 
Closes #87
This branch removes the `span::Data` type from `tokio-trace-core` and
replaces it with a new `span::Attributes` type, which does not track the
span's field values. 
Since the `Data` type might still be useful for subscriber
implementations, it is still provided in the `tokio-trace` crate, but is
no longer part of `core`.
This also includes the changes in PR #87, which  changes `Data` to only
allocate when `add_value` is called, rather than in `new`. It will now
only grow the vector the desired amount to store another value. Thus, if
a subscriber does not wish to allocate, the allocation will never take
place. When `add_data` is called and the vector is empty, we reserve
enough capacity to store all the fields, so we still only perform a
single allocation. …
=> Remove `span::Data` from `tokio-trace-core`

tokio-trace-core/src/callsite.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/span.rs, tokio-trace-log/src/lib.rs, tokio-trace/Cargo.toml, tokio-trace/benches/no_subscriber.rs, tokio-trace/src/lib.rs
Currently, the `Callsite::is_enabled` function requires a reference to a
dispatcher. This is used to filter the callsite when the cached interest
is `Interest::SOMETIMES`. However, it means we must always get the
current dispatcher, even when the interest is `NEVER`.
This branch replaces `Callsite::is_enabled` with a `Callsite::interest`
function that just returns the cached interest. This no longer requires
a reference to a dispatcher. The `Span::new` and `Event::observe`
functions have been rewritten to only get the dispatcher if the interest
is `ALWAYS` or `SOMETIMES`.
This results in a major performance improvement in the case where a span
is disabled, putting our performance within the same order of magnitude
as the `log` crate's performance when there's no logger.
Benchmark results …
=> Don't get the dispatcher when the cached interest is NEVER

tokio-trace-core/src/span.rs, tokio-trace-core/src/subscriber.rs, tokio-trace/src/lib.rs
Inlining the small functions called in the callsite filtering path seems
to improve the performance of disabled spans enough that the overhead is
now about on par with the `log` crate.
Benchmarks for this branch:
```
Running target/release/deps/no_subscriber-9e181e53a6cbc952
running 5 tests
test bench_1_atomic_load              ... bench:           0 ns/iter (+/- 0)
test bench_costly_field_no_subscriber ... bench:           1 ns/iter (+/- 0)
test bench_log_no_logger              ... bench:           1 ns/iter (+/- 0)
test bench_no_span_no_subscriber      ... bench:           0 ns/iter (+/- 0)
test bench_span_no_subscriber         ... bench:           1 ns/iter (+/- 0)
test result: ok. 0 passed; 0 failed; 0 ignored; 5 measured; 0 filtered out
Running …
```
=> Inline the hottest callsite filtering functions

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/span.rs
Closes #84.
This branch replaces `Dispatch::current` with a function that runs a
closure on the current dispatcher using `CURRENT_DISPATCH.with(...)`,
and only clones the dispatcher when it's necessary to do so to construct
a new enabled span. 
On my machine, this change has relatively little performance impact, but
on platforms where an arc bump is more costly, this is likely a significant
performance improvement:
```
running 5 tests
test bench_1_atomic_load              ... bench:           0 ns/iter (+/- 0)
test bench_costly_field_no_subscriber ... bench:           1 ns/iter (+/- 0)
test bench_log_no_logger              ... bench:           1 ns/iter (+/- 0)
test bench_no_span_no_subscriber      ... bench:           0 ns/iter (+/- 0)
test bench_span_no_subscriber         ... bench: …
```
=> Reduce current dispatcher Arc clones

tokio-trace-core/src/span.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-log/src/lib.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/span.rs
This branch rewrites the `RecordError` and `FollowsError` types so that
the publicly-exposed type is a struct, rather than an enum. Consumers of
the API may still test what type of error occurred with a set of
`is_{error kind}` methods, but new error kinds may now be added without
causing a breaking change, as the struct cannot be matched against.
This is required for #73.
=> Make subscriber errors forwards-compatible

tokio-trace-core/src/dispatcher.rs, tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-futures/src/lib.rs, tokio-trace-macros/examples/basic.rs, tokio-trace-subscriber/src/filter.rs, tokio-trace-subscriber/src/observe.rs, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace/benches/subscriber.rs, tokio-trace/examples/basic.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/main.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
@carllerche suggested that this naming was unclear, so I've
renamed the constructor to follow the conventional naming
scheme.
This is in service of #72
=> Rename `Dispatch::to` to `Dispatch::new`

tokio-trace-core/src/lib.rs, tokio-trace-log/src/lib.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs
Since events no longer have to be constructed as struct initializers, we
can remove its fields from the public API.
This is in service of #73.
=> Make event fields private and replace with accessors

tokio-trace-core/src/lib.rs, tokio-trace/src/lib.rs
Closes #98 
This branch allows the `event!` macro to actually construct and pass in
a slice of IDs that a span follows from. It also adds a function on
`Event` returning the IDs of the spans that the event follows from.
The syntax in the macro isn't _great_ --- it's a little verbose.
Possibly this will need another pass prior to stabilizing the macros
=> Add support for `follows_from` in the `event!` macro

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/field.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/span.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/lib.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace/benches/subscriber.rs, tokio-trace/examples/basic.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/field.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs
This branch changes the implementation of the `Event` type so that
`Event`s are now implemented on top of the same internals as `Span`s.
The `Subscriber::observe_event` function has been removed; events are
now created by calls to `Subscriber::new_id`, populated by calls to
`Subscriber::record` and `Subscriber::follows_from` with the event's ID,
and completed by `Subscriber::close`. 
This change was made primarily because it allows the `Record` trait to
be removed from `tokio-trace-core`. Since `Event`s now have IDs, fields
on them can be recorded through the same mechanism as `Span`s; a
separate `Record` type that provides context is no longer necessary. The
methods on `Record` have been replaced with `Subscriber` trait methods
with the same behaviour. 
This also will allow us to remove …
=> Make `Event`s more similar to `Span`s

tokio-trace-core/src/field.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/span.rs, tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-macros/examples/basic.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace-tower-http/src/lib.rs, tokio-trace-tower/src/lib.rs, tokio-trace/benches/no_subscriber.rs, tokio-trace/benches/subscriber.rs, tokio-trace/examples/basic.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/main.rs, tokio-trace/src/field.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs
This branch removes the `Value` trait from `tokio-trace-core`.
Since the dispatch of value types to subscriber methods which that
trait provided was really only necessary for the `event!` and `span!`
macros in the `tokio-trace` crate, it was moved to that crate. This
simplifies `core`'s field module significantly, and doesn't require
this trait to be part of the stable API (yet).
=> Remove `Value` trait from `tokio-trace-core`

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/span.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace/benches/subscriber.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/field.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs
Closes #104. 
This branch removes the `Result` return types from `Subscriber` trait
methods in `tokio-trace-core`. We can still add a fallible subscriber
type later, but that won't require a change to core.
This has the side benefit of making span and event
`follows_from`/`record_$TY` methods chainable.
=> Remove errors from `core::Subscriber`

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/field.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/span.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-futures/src/lib.rs, tokio-trace-log/src/lib.rs, tokio-trace-macros/examples/basic.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/filter.rs, tokio-trace-subscriber/src/lib.rs, tokio-trace-subscriber/src/observe.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace-tower-http/src/lib.rs, tokio-trace-tower/src/lib.rs, tokio-trace/benches/no_subscriber.rs, tokio-trace/benches/subscriber.rs, tokio-trace/examples/basic.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/main.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/field.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
Partially addresses #39. I can created macros for other levels, but I personally think the primary levels that we should support are trace/info and error.
=> Add Ergonomic event macros, closes #39 and #74.

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/span.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-futures/Cargo.toml, tokio-trace-futures/src/lib.rs, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/observe.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace/examples/basic.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/dispatcher.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
Closes #60.
This branch moves the responsibility for tracking the current span out
of `core` and onto the `Subscriber` trait. This makes core responsible
for less and allows subscriber implementations to choose how this should
be tracked,
This change ended up being fairly large. In order to make subscribers
responsible for tracking the current span, the subscriber API needed to
change. Furthermore, several changes to the span entry, exit, and
closure logic were required. Additionally, the test changes I wrote to
verify this branch caught a few additional issues in the span closure
logic, so I've fixed those as well.
I've added a type that tracks the current thread using a thread-local in
the `tokio-trace` crate. This implements approximately the same
behaviour that core provided before …
=> Make subscribers responsible for tracking the current span

.travis.yml, tokio-trace-core/src/callsite.rs, tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/span.rs, tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-futures/src/lib.rs, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/observe.rs
Closes #108 
This branch adds a Rust 1.26.0 CI build, and changes all the crates
except for `tokio-trace-macros` to work with Rust 1.26.0.
I don't know if it's possible to make the proc macros work with Rust
1.26.0, but since they're not core, it doesn't matter as much. Thus,
they're only built in a separate CI job that builds against stable.
=> Support Rust 1.26.0

tokio-trace-core/src/callsite.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-log/src/lib.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs
Depends on #123.
Closes #115.
Closes #120.
Closes #121.
This branch makes several minor changes to the `Callsite` and 
`Interest` types: 
+ Remove the `Interest::from_usize` and `Interest::as_usize` 
conversions, as they create a forward-compatibility hazard.
+ Remove the `Callsite::interest` method, as it was not strictly
necessary.
+ Rename `Callsite::remove_interest` to `clear_interest`, which
more accurately describes the method's behaviour.
=> Make `Callsite` less `Interest`ing

tokio-trace-core/src/lib.rs, tokio-trace-log/src/lib.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs
Closes #118 
This branch replaces the public `Level` enum with a struct so that the
variants can be changed without causing a breaking change. The variants
are now represented as associated constants (similarly to `Interest`) so
that they may still be used in a static context.
=> Make `Level` a struct rather than an enum

tokio-trace-core/src/field.rs, tokio-trace-core/src/metadata.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-log/src/lib.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs
This branch removes several unnecessary derived traits from types in
`tokio-trace-core`:
+ `Interest` no longer derives `Copy`, `Eq`, `PartialEq`, `Ord`, and
`PartialOrd` (#146). New `is_never`/`is_sometimes`/`is_always` 
methods allow  checking an `Interest` without using equality, 
although this interface is admittedly somewhat more cumbersome.
+ `Fields` no longer derives `Clone` (#139).
+ `metadata::Level` no longer derives `Copy` and `Hash`.
+ `metadata::Kind` no longer derives `Copy`, `Hash`, `PartialEq`,
and `Eq` (as it has `is_span`/`is_event` methods already).
@carllerche, do you think this is sufficient to close #147, or are
there more derived traits that you think ought to be removed?
Closes #146.
Closes #139.
=> Remove unneeded derived traits

tokio-trace-core/src/callsite.rs, tokio-trace-core/src/field.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/subscriber.rs
This branch removes unneeded and unused code from `tokio-trace-core`'s
API. In particular, I've removed `field::Key::as_usize`,
`subscriber::Interest::from_filter`, and the dead code `Sealed` trait.
Closes #148.
Closes #143.
Closes #145.
Closes #148.
=> Remove some unneeded APIs

tokio-trace-core/src/callsite.rs, tokio-trace-core/src/field.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/metadata.rs, tokio-trace-log/src/lib.rs, tokio-trace/src/field.rs, tokio-trace/src/lib.rs
This branch adds a `metadata!` macro in `tokio-trace-core` that
constructs a set of metadata, and updates the `callsite!` macro in
`tokio-trace` to use this.
I've also changed `callsite::Identifier` to allow it to be constructed
in a static context. This allows `field::Fields` to hold an `Identifier`
rather than a `Callsite` trait object pointer (#138). I've also changed
methods returning `Identifier`s to be named `.callsite()` rather than
`.id()` (#140). 
Closes #150.
Closes #140.
Closes #138.
=> Add `metadata!` macro and update naming

tokio-trace-core/src/callsite.rs, tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/field.rs, tokio-trace-core/src/lib.rs, tokio-trace-core/src/metadata.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-subscriber/src/filter.rs, tokio-trace-subscriber/src/observe.rs, tokio-trace-subscriber/src/registry.rs, tokio-trace/benches/subscriber.rs, tokio-trace/examples/counters.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/field.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs
This branch renames some types and functions in `tokio-trace-core` and
`tokio-trace`:
+ Rename `field::Key` to `field::Field`.
+ Rename `tokio-trace::AsKey` to `tokio-trace::AsField`, and rename 
functions whose names refer to "key"s to refer to "field"s instead.
+ Rename `field::Fields` to `FieldSet`.
+ Rename `Meta` to `Metadata`.
I've also updated some docs and comments to read better with the new 
names.
Closes: #142 
Closes: #144
Refs: #72
=> Core API naming pass

tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-futures/src/executor.rs, tokio-trace-log/src/lib.rs, tokio-trace-macros/src/lib.rs, tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace-tower-http/src/lib.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/span.rs, tokio-trace/src/subscriber.rs
Looks like the rustfmt formatting rules on stable changed between Rust
1.30.0 and 1.31.0. This branch reformats everything with the latest 
stable.
=> Reformat with 1.31.0 stable rustfmt

Cargo.toml, tokio-trace-tower-http/Cargo.toml, tokio-trace-tower-http/src/lib.rs
Update for compatibility with tower-rs/tower@ac1586748f5505336573f8829d22ad7bbcda825a.
This should fix the CI builds.
=> Update Tower compatibility 

tokio-trace-core/src/dispatcher.rs, tokio-trace-core/src/metadata.rs, tokio-trace-core/src/subscriber.rs, tokio-trace-env-logger/examples/hyper-echo.rs, tokio-trace-futures/src/executor.rs, tokio-trace-futures/src/lib.rs, tokio-trace-log/src/lib.rs, tokio-trace-subscriber/src/compose.rs, tokio-trace-tower-http/src/lib.rs, tokio-trace-tower/src/lib.rs, tokio-trace/examples/sloggish/sloggish_subscriber.rs, tokio-trace/src/span.rs
This branch removes the `Subscriber::new_static` function, so that all
spans are created through the `Subscriber::new_span` function. It also
removes the restriction that all spans must have `'static` metadata.
Spans are now generic over the lifetime of their metadata.
Closes #137 
=> Remove `Subscriber::new_static`

tokio-trace-tower-http/examples/tower-h2-server.rs, tokio-trace/src/lib.rs
This branch changes the "`log`-like" event macros (`error!`, `warn!`,
`info!`, `debug!`, and `trace!`, when used without fields) to expand to
an expression returning `()`, rather than an `Event`. 
This change makes it easier to use `tokio-trace` as a drop-in
replacement for the `log` crate. Since these macros previously returned
a value, they couldn't be used in cases where, for example, a value was
logged and discarded in order to make a `Future`'s `Item` or `Error`
types `()`, without changing the syntax.
For example, the following code works with `log`, but not `tokio-trace`:
```rust
fn foo() -> impl Future<Item = (), Error = ()> {
future::lazy(...)
// ...
.map_err(|e| error!("error: {:?}", e))
.map(|_| ())
}
```
Since `tokio-trace`'s macros previously returned an `event` when
used in …
=> Change log-like event macros to expand to ()

tokio-trace-futures/src/lib.rs
This branch adds some simple wrapper functions to the `Instrumented` and
`WithDispatch` types in the `tokio-trace-futures` crate, allowing access
to the wrapped type, and to the `Span` or `Dispatch` that wraps that
type.
=> futures: Add some utility functions

tokio-trace-futures/Cargo.toml, tokio-trace-futures/src/executor.rs, tokio-trace-futures/src/lib.rs
Currently, the `tokio-trace-futures` crate has types which wrap values
implementing the `futures::Executor` trait. Although `tokio` provides
executors implementing this trait, it also has its own `Executor` trait,
and provides runtime types with other functions which also spawn or run
futures, such as `block_on`. The `InstrumentedExecutor` and
`WithDispatch` types currently do not implement `tokio`'s `Executor`
trait or other useful functions, so a wrapped tokio `Runtime` or
`Executor` may only be interacted with through its `futures::Executor`
implementation.
This branch adds new impls for `WithDispatch` and
`InstrumentedExecutor` for `tokio`'s `Executor` trait and runtime types.
Commonly-used functions on `tokio`'s `Runtime` and
`current_thread::Runtime` (`block_on`, `spawn`, and …
=> Add impls for tokio types to the `tokio-trace-futures` crate

tokio-trace-log/src/lib.rs, tokio-trace/src/lib.rs, tokio-trace/src/span.rs
Currently, the `Span::new` and `Event::new` constructors take closures
which are executed if the span or event is enabled. These closures are
used by the `span!` and `event!` macros to add fields to the span.
However, while replacing uses of the `log` crate in Linkerd 2's proxy
with `tokio-trace`, I noticed that the use of closures here causes some
borrow checker errors with macro invocations which work under the log
crate. When a format argument passed to a macro invocation is later
borrowed mutably in the same scope, the compiler produces errors like
this one:
```
error[E0502]: cannot borrow `self` as immutable because `self.state.0` is also borrowed as mutable
--> src/app/profiles.rs:188:25
|
181 |                 State::Waiting(ref mut f) => match f.poll() {
| …
```
=> Remove closures from Span and Event constructors
